# Generated by Django 4.2.7 on 2026-03-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_auth_app', '0001_initial'),
    ]

    operations = [
    ]
