# Generated by Django 4.2.7 on 2026-03-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_auth_app', '0002_auto_20260312_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsession',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
