# Generated by Django 4.2.7 on 2026-03-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_auth_app', '0003_alter_loginsession_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceuser',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
